# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    environment: maven-publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: lionarius-reposilite
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        MINESKIN_API_KEY: ${{ secrets.MINESKIN_API_KEY }}

    - name: Publish to Reposilite
      run: mvn deploy
      env:
        MAVEN_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
